package hibernate;
// Generated Mar 24, 2014 3:50:10 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String id;
     private String password;
     private String name;
     private String email;
     private String phone;
     private String address;
     private String adminFlag;
     private Set customerOrders = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String id, String password, String name, String email, String phone, String address, String adminFlag) {
        this.id = id;
        this.password = password;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.adminFlag = adminFlag;
    }
    public Customer(String id, String password, String name, String email, String phone, String address, String adminFlag, Set customerOrders) {
       this.id = id;
       this.password = password;
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.adminFlag = adminFlag;
       this.customerOrders = customerOrders;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAdminFlag() {
        return this.adminFlag;
    }
    
    public void setAdminFlag(String adminFlag) {
        this.adminFlag = adminFlag;
    }
    public Set getCustomerOrders() {
        return this.customerOrders;
    }
    
    public void setCustomerOrders(Set customerOrders) {
        this.customerOrders = customerOrders;
    }




}


