package hibernate;
// Generated Mar 24, 2014 3:50:10 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String name;
     private BigDecimal price;
     private String description;
     private String detail;
     private byte[] image;
     private Date lastUpdate;
     private String sellerId;
     private Set productOrders = new HashSet(0);

    public Product() {
    }

	
    public Product(Category category, String name, BigDecimal price, Date lastUpdate) {
        this.category = category;
        this.name = name;
        this.price = price;
        this.lastUpdate = lastUpdate;
    }
    public Product(Category category, String name, BigDecimal price, String description, String detail, byte[] image, Date lastUpdate, Set productOrders) {
       this.category = category;
       this.name = name;
       this.price = price;
       this.description = description;
       this.detail = detail;
       this.image = image;
       this.lastUpdate = lastUpdate;
       this.productOrders = productOrders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set productOrders) {
        this.productOrders = productOrders;
    }

    public String getSellerId() {
        return sellerId;
    }

    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }



}


