package hibernate;
// Generated Mar 24, 2014 3:50:10 PM by Hibernate Tools 3.6.0



/**
 * ProductOrder generated by hbm2java
 */
public class ProductOrder  implements java.io.Serializable {


     private ProductOrderId productOrderId;
     private Product product;
     private CustomerOrder customerOrder;
     private short quantity;

    public ProductOrderId getProductOrderId() {
        return productOrderId;
    }

    public void setProductOrderId(ProductOrderId productOrderId) {
        this.productOrderId = productOrderId;
    }

    public ProductOrder() {
    }

    public ProductOrder(ProductOrderId id, Product product, CustomerOrder customerOrder, short quantity) {
       this.productOrderId = id;
       this.product = product;
       this.customerOrder = customerOrder;
       this.quantity = quantity;
    }
    
    public ProductOrder(ProductOrderId productOrderId) {
        this.productOrderId = productOrderId;
    }

    public ProductOrder(ProductOrderId productOrderId, short quantity) {
        this.productOrderId = productOrderId;
        this.quantity = quantity;
    }

    public ProductOrder(String customerOrderId, int productId) {
        this.productOrderId = new ProductOrderId(customerOrderId, productId);
    }

   
    public ProductOrderId getId() {
        return this.productOrderId;
    }
    
    public void setId(ProductOrderId id) {
        this.productOrderId = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public CustomerOrder getCustomerOrder() {
        return this.customerOrder;
    }
    
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }
    public short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(short quantity) {
        this.quantity = quantity;
    }




}


