package hibernate;
// Generated Mar 24, 2014 3:50:10 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrder  implements java.io.Serializable {


     private String id;
     private Customer customer;
     private BigDecimal amount;
     private Date dateCreated;
     private String modePayment;
     private String cardNumber;
     private int confirmationNumber;
     private Set productOrders = new HashSet(0);

    public CustomerOrder() {
    }

	
    public CustomerOrder(String id, Customer customer, BigDecimal amount, Date dateCreated, int confirmationNumber) {
        this.id = id;
        this.customer = customer;
        this.amount = amount;
        this.dateCreated = dateCreated;
        this.confirmationNumber = confirmationNumber;
    }
    public CustomerOrder(String id, Customer customer, BigDecimal amount, Date dateCreated, String modePayment, String cardNumber, int confirmationNumber, Set productOrders) {
       this.id = id;
       this.customer = customer;
       this.amount = amount;
       this.dateCreated = dateCreated;
       this.modePayment = modePayment;
       this.cardNumber = cardNumber;
       this.confirmationNumber = confirmationNumber;
       this.productOrders = productOrders;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getModePayment() {
        return this.modePayment;
    }
    
    public void setModePayment(String modePayment) {
        this.modePayment = modePayment;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public int getConfirmationNumber() {
        return this.confirmationNumber;
    }
    
    public void setConfirmationNumber(int confirmationNumber) {
        this.confirmationNumber = confirmationNumber;
    }
    public Set getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set productOrders) {
        this.productOrders = productOrders;
    }




}


