package hibernate;
// Generated Mar 24, 2014 3:50:10 PM by Hibernate Tools 3.6.0



/**
 * ProductOrderId generated by hbm2java
 */
public class ProductOrderId  implements java.io.Serializable {


     private String customerOrderId;
     private int productId;

    public ProductOrderId() {
    }

    public ProductOrderId(String customerOrderId, int productId) {
       this.customerOrderId = customerOrderId;
       this.productId = productId;
    }
   
    public String getCustomerOrderId() {
        return this.customerOrderId;
    }
    
    public void setCustomerOrderId(String customerOrderId) {
        this.customerOrderId = customerOrderId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductOrderId) ) return false;
		 ProductOrderId castOther = ( ProductOrderId ) other; 
         
		 return ( (this.getCustomerOrderId()==castOther.getCustomerOrderId()) || ( this.getCustomerOrderId()!=null && castOther.getCustomerOrderId()!=null && this.getCustomerOrderId().equals(castOther.getCustomerOrderId()) ) )
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomerOrderId() == null ? 0 : this.getCustomerOrderId().hashCode() );
         result = 37 * result + this.getProductId();
         return result;
   }   


}


